version: '3'

services:
  etcd:
    image: "quay.io/coreos/etcd:v3.3"
    container_name: "etcd"
    restart: always
    hostname: etcd
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: "3"
    volumes:
      - ./data/etcd/default.etcd:/default.etcd
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
  etcdkeeper:
    image: "evildecay/etcdkeeper"
    container_name: "etcdkeeper"
    restart: always
    environment:
      Host: "0.0.0.0"
    ports:
      - 8092:8080
    depends_on:
      - etcd

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    restart: always
    hostname: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mqtt:/mosquitto/config
      - ./data/mqtt/data:/mosquitto/data
      - ./data/mqtt/log:/mosquitto/log
    privileged: true

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin


  consul:
    image: consul:latest
    container_name: consul
    restart: always
    hostname: consul
    ports:
      - "8500:8500"
    command: [ "consul","agent","-server","-bootstrap","-data-dir","/consul","-ui","-bind","127.0.0.1","-client","0.0.0.0" ]

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./init/mysql:/docker-entrypoint-initdb.d/
      - ./data/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nacos_config
      MYSQL_USER: nacos
      MYSQL_PASSWORD: nacos
    #privileged: true

  nacos:
    image: nacos/nacos-server:v2.2.0
    container_name: nacos
    restart: always
    hostname: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=UTC
    volumes:
      - ./data/nacos/logs/:/home/nacos/logs
      - ./data/nacos/plugins/:/home/nacos/plugins
      - ./config/nacos/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    restart: always
    hostname: zookeeper
    ports:
      - "2181:2181"
      - "8081:8080"
    volumes:
      - "./data/zookeeper/data:/data"
      - "./data/zookeeper/datalog:/datalog"
      - "./data/zookeeper/logs:/logs"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    restart: always
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      # 客户端访问地址，更换成自己的
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.20.99:9092
      # 自动创建 topic 功能
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    restart: always
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    links:
      - kafka
    external_links:
      - zookeeper
    environment:
      - ZK_HOSTS=zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
